version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    command: >
      sh -c "env $$(cat /app/.env | xargs) ./cmd migrate && env $$(cat /app/.env | xargs) ./cmd server"

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
