CREATE TABLE users (
	id VARCHAR (255) PRIMARY KEY,
	phone_number VARCHAR (16) UNIQUE NOT NULL,
	full_name VARCHAR (255) NOT NULL,
	password VARCHAR(200) NOT NULL,
	password_salt VARCHAR(200) NOT NULL,
	created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP
);
