CREATE TABLE news (
	id VARCHAR (255) PRIMARY KEY,
	title VARCHAR (255) UNIQUE NOT NULL,
	description TEXT NOT NULL,
	created_at timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
